/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package solving.nonlinear.equations;

import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTFa = new javax.swing.JTextField();
        jLa = new javax.swing.JLabel();
        jTFb = new javax.swing.JTextField();
        jLb = new javax.swing.JLabel();
        jTFc = new javax.swing.JTextField();
        jLc = new javax.swing.JLabel();
        jTFd = new javax.swing.JTextField();
        jLres = new javax.swing.JLabel();
        jLa0 = new javax.swing.JLabel();
        jTFa0 = new javax.swing.JTextField();
        jLb0 = new javax.swing.JLabel();
        jTFb0 = new javax.swing.JTextField();
        jBtnInput = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblBisection = new javax.swing.JTable();
        jBtnSimpleIter = new javax.swing.JButton();
        jBtnNuton = new javax.swing.JButton();
        jBtnChord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLa.setText("x^3 +");

        jLb.setText("x^2 +");

        jLc.setText("x +");

        jLres.setText(" = 0");

        jLa0.setText("a0 :");

        jLb0.setText("b0 :");

        jBtnInput.setText("Половинного деления");
        jBtnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInputActionPerformed(evt);
            }
        });

        modelBisection = new DefaultTableModel(new Object[]{"n","an","xn","bn","f(an)","f(xn)","f(bn)"}, 0);
        jTblBisection.setModel(modelBisection);
        jScrollPane1.setViewportView(jTblBisection);

        jBtnSimpleIter.setText("Простой итерации");
        jBtnSimpleIter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSimpleIterActionPerformed(evt);
            }
        });

        jBtnNuton.setText("Ньютон");
        jBtnNuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNutonActionPerformed(evt);
            }
        });

        jBtnChord.setText("Хорд");
        jBtnChord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLres)
                        .addGap(27, 27, 27)
                        .addComponent(jLa0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFa0, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLb0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFb0, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnInput)
                    .addComponent(jBtnSimpleIter)
                    .addComponent(jBtnNuton)
                    .addComponent(jBtnChord))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLa)
                    .addComponent(jTFb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb)
                    .addComponent(jTFc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLc)
                    .addComponent(jTFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLres)
                    .addComponent(jLa0)
                    .addComponent(jTFa0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb0)
                    .addComponent(jTFb0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnSimpleIter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnNuton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnChord)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Численные методы", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInputActionPerformed
        int k = modelBisection.getRowCount();
        for(int i=0;i<k;i++){
            modelBisection.removeRow(0);
        }
        NumberFormat f = NumberFormat.getInstance();
        f.setGroupingUsed(false);
       // Function func;
        func = new Function(Double.parseDouble(jTFa.getText()), Double.parseDouble(jTFb.getText()), Double.parseDouble(jTFc.getText()), Double.parseDouble(jTFd.getText()));
        func.setStartPoint(Double.parseDouble(jTFa0.getText()), Double.parseDouble(jTFb0.getText()));
        double count = 0;
        for(Iteration iter : func.bisection()){
            Vector<String> vec = new Vector<>();
            vec.add(""+count++);
            vec.add(f.format(iter.getA()));
            vec.add(f.format(iter.getX()));
            vec.add(f.format(iter.getB()));
            vec.add(f.format(func.f(iter.getA())));
            vec.add(f.format(func.f(iter.getX())));
            vec.add(f.format(func.f(iter.getB())));
            modelBisection.addRow(vec);
        }
    }//GEN-LAST:event_jBtnInputActionPerformed

    private void jBtnNutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNutonActionPerformed
        modelBisection = new DefaultTableModel(new Object[]{"n", "xn", "f(xn)","delta(xn)","f(xn)/m1"}, 0);
        ArrayList<Iteration> nuton = func.nuton();
        int n=0;
        for(Iteration iter : nuton){
            modelBisection.addRow(new Object[]{n, iter.getX(), func.f(iter.getX()), iter.getB(), iter.getA()});
            n++;
        }
        jTblBisection.setModel(modelBisection);
    }//GEN-LAST:event_jBtnNutonActionPerformed

    private void jBtnChordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnChordActionPerformed
        modelBisection = new DefaultTableModel(new Object[]{"n", "xn", "f(xn)","delta(xn)","f(xn)/m1"}, 0);
        ArrayList<Iteration> chord = func.chord();
        int n=0;
        for(Iteration iter : chord){
            modelBisection.addRow(new Object[]{n, iter.getX(), func.f(iter.getX()), iter.getB(), iter.getA()});
            n++;
        }
        jTblBisection.setModel(modelBisection);
    }//GEN-LAST:event_jBtnChordActionPerformed

    private void jBtnSimpleIterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSimpleIterActionPerformed
        modelBisection = new DefaultTableModel(new Object[]{"n", "xn", "f(xn)","f(xn)/m1"}, 0);
        ArrayList<Iteration> chord = func.simpleIteration();
        int n=0;
        for(Iteration iter : chord){
            modelBisection.addRow(new Object[]{n, iter.getX(), func.f(iter.getX()), iter.getA()});
            n++;
        }
        jTblBisection.setModel(modelBisection);
    }//GEN-LAST:event_jBtnSimpleIterActionPerformed

 
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnChord;
    private javax.swing.JButton jBtnInput;
    private javax.swing.JButton jBtnNuton;
    private javax.swing.JButton jBtnSimpleIter;
    private javax.swing.JLabel jLa;
    private javax.swing.JLabel jLa0;
    private javax.swing.JLabel jLb;
    private javax.swing.JLabel jLb0;
    private javax.swing.JLabel jLc;
    private javax.swing.JLabel jLres;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFa;
    private javax.swing.JTextField jTFa0;
    private javax.swing.JTextField jTFb;
    private javax.swing.JTextField jTFb0;
    private javax.swing.JTextField jTFc;
    private javax.swing.JTextField jTFd;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTblBisection;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelBisection;
    Function func;
}
